version: "3.9"
services:
    php74_apache:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "8089:80"
        volumes:
            - ./src:/var/www/html
            - ./conf/apache:/etc/apache2/sites-enabled/